import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/components/Providers";
import Navbar from "@/components/Navbar";
import { notoSans, patrickHand, poppins, roboto } from "@/ui/fonts";

export const metadata: Metadata = {
  title: "Chill Study",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.png",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}  ${roboto.variable}  ${patrickHand.variable} ${notoSans.variable} antialiased text-black`}>
        <Providers>
          <main>
            <Navbar />

            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
